/**
 * The `.github\copilot-instructions.md` half of client setup.
 *
 * `.mcp.json` only tells the IDE how to *start* the server; without the
 * instructions file in a parent of the solution folder Copilot keeps using its
 * built-in file tools and edits X++ behind the metadata provider's back. Both
 * files therefore have to be placed for a working install, so the wizards
 * offer to put this one down as well — either straight into the solutions
 * folder, or, when that is unknown, into a staging folder with a README
 * naming the two destinations.
 *
 * The README points at the one .mcp.json `mcpJsonNote()` writes in the data
 * root rather than copying it: the staging folder sits in that same data
 * root, so a second copy is only one more file to keep in sync.
 *
 * Shared by `setup` (scenarios B–E) and `instance add` (scenario F), which
 * both end on the same two-file placement step.
 */
import * as fs from 'node:fs';
import { resolve } from 'node:path';
import { dataRoot, paths, repoRoot } from './context.js';
import { askConfirm, p } from './ui.js';

/** The copy shipped with this installation — package root in both install modes. */
const copilotSource = (): string => resolve(repoRoot, '.github', 'copilot-instructions.md');

function writeCopilotSetupReadme(targetDir: string, opts: { copilotAlreadyPlaced: boolean }): void {
  const readmePath = resolve(targetDir, 'README.md');
  const lines = [
    '# VS setup quick guide',
    '',
    'This file is generated by `d365fo-mcp setup` to simplify Visual Studio onboarding.',
    '',
    '1. Copy .mcp.json',
    '   - Recommended (all solutions): %USERPROFILE%\\.mcp.json',
    '   - Per solution: place .mcp.json next to your .sln file',
    `   - Generated copy: ${paths.mcpSuggestion}`,
    '',
    '2. Copy .github/copilot-instructions.md',
    opts.copilotAlreadyPlaced
      ? '   - Already placed here: .github\\copilot-instructions.md'
      : '   - Destination: a parent folder of your solution directories',
    '   - Why: provides mandatory D365FO tool-routing and safety rules for Copilot',
    '',
    '3. Restart Visual Studio after copying files.',
  ];
  fs.writeFileSync(readmePath, lines.join('\n') + '\n', 'utf8');
}

/**
 * Offer to place copilot-instructions.md, falling back to a staging folder.
 *
 * `solutionsPath` is what the user gave for workspace.solutionsPath; when it
 * is empty there is nowhere to copy to, so the file is staged instead and the
 * README says where it has to end up.
 */
export async function maybePrepareCopilotInstructions(solutionsPath: string): Promise<void> {
  const source = copilotSource();
  if (!fs.existsSync(source)) {
    p.log.warn(
      'Cannot find copilot-instructions.md in this installation; skipping copy helper.\n' +
      `   Looked for: ${source}`,
    );
    return;
  }

  const wantsDirectCopy = await askConfirm(
    'Create/copy .github/copilot-instructions.md into the solutions folder now?',
    true,
  );
  const target = solutionsPath.trim();

  if (wantsDirectCopy && target) {
    const targetDir = resolve(target, '.github');
    fs.mkdirSync(targetDir, { recursive: true });
    fs.copyFileSync(source, resolve(targetDir, 'copilot-instructions.md'));
    writeCopilotSetupReadme(target, { copilotAlreadyPlaced: true });
    p.log.success(`Prepared: ${resolve(targetDir, 'copilot-instructions.md')}`);
    p.log.success(`Prepared: ${resolve(target, 'README.md')}`);
    return;
  }

  const stageDir = resolve(dataRoot(), 'copilot-setup');
  const stageGitHubDir = resolve(stageDir, '.github');
  fs.mkdirSync(stageGitHubDir, { recursive: true });
  fs.copyFileSync(source, resolve(stageGitHubDir, 'copilot-instructions.md'));
  writeCopilotSetupReadme(stageDir, { copilotAlreadyPlaced: false });

  if (wantsDirectCopy && !target) {
    p.log.warn('Solutions folder is empty, so files were prepared in the local staging folder instead.');
  } else {
    p.log.info('Copy was skipped; files were prepared in a local staging folder for later use.');
  }
  p.log.info(`Staging folder: ${stageDir}`);
}
