/**
 * Regenerates docs/CONFIGURATION.md from the setting registry, so the reference
 * table can never drift from what the wizard actually asks for.
 *
 *   npm run config:docs
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SECTIONS, SETTINGS, type Setting } from '../src/config/settings.js';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(repoRoot, 'docs', 'CONFIGURATION.md');

const TIER_LABEL: Record<Setting['tier'], string> = {
  basic: 'setup',
  advanced: 'advanced',
  secret: 'secret',
};

function formatDefault(setting: Setting): string {
  if (setting.default === undefined) return '—';
  const value = Array.isArray(setting.default) ? setting.default.join(',') : String(setting.default);
  return value === '' ? '—' : '`' + value + '`';
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function exampleValue(setting: Setting): unknown {
  if (setting.default !== undefined) return setting.default;
  if (setting.choices?.length) return setting.choices[0].value;
  if (setting.placeholder) return setting.placeholder;
  return setting.type === 'boolean' ? false : setting.type === 'int' ? 0 : '';
}

function buildExample(tier: 'config' | 'secret'): string {
  const out: Record<string, any> = tier === 'config' ? { version: 1 } : {};
  for (const setting of SETTINGS) {
    if (tier === 'config' ? setting.tier === 'secret' : setting.tier !== 'secret') continue;
    const keys = setting.path.split('.');
    const last = keys.pop()!;
    let cursor = out;
    for (const key of keys) {
      cursor[key] ??= {};
      cursor = cursor[key];
    }
    cursor[last] = tier === 'secret' ? '<secret>' : exampleValue(setting);
  }
  return JSON.stringify(out, null, 2);
}

const lines: string[] = [
  '# Configuration reference',
  '',
  '<!-- Generated by scripts/generate-config-docs.ts — run `npm run config:docs` after changing src/config/settings.ts. -->',
  '',
  'Run `npm run setup`; it asks for what your deployment scenario needs and writes',
  '`config/d365fo-mcp.json` (plus `config/secrets.json` when a secret is involved).',
  'Nothing here has to be edited by hand — the tables document what the wizard stores.',
  '',
  'To change something later without walking the whole wizard:',
  '',
  '```powershell',
  'npx d365fo-mcp config              # pick an area, answer only its questions',
  'npx d365fo-mcp config naming       # straight to one section',
  'npx d365fo-mcp config --xpp-config # repick the pinned UDE config',
  'npx d365fo-mcp config --instance clientA',
  '```',
  '',
  'The `.mcp.json` block printed by the wizard passes `D365FO_CONFIG` in its `env`',
  'block, so the IDE-spawned server finds this file no matter what directory it is',
  'started from. Adding any other variable to that block overrides the config file',
  'for that one server entry — that is how a per-solution `D365FO_MODEL_NAME` is set.',
  '',
  '## How a value is resolved',
  '',
  'First source that defines a variable wins:',
  '',
  '1. **The real environment** — shell, the `env` block of `.mcp.json`, Azure App Settings.',
  '2. **A `.env` named explicitly via `ENV_FILE`** — a profile you picked on purpose',
  '   (`ENV_FILE=.env.eval`) still outranks the config file.',
  '3. **`config/d365fo-mcp.json` + `config/secrets.json`** — written by the wizard.',
  '4. **The ambient repo-root `.env`** — pre-wizard installations keep working;',
  '   `d365fo-mcp doctor` reports any key where the two files disagree.',
  '',
  'Instances keep their own `instances/<name>/d365fo-mcp.json`; point a process at one',
  'explicitly with `D365FO_CONFIG=<path to the json>`. Relative paths inside a config',
  'file resolve from that file\'s directory, so instance folders stay movable.',
  '',
  'The **Env var** column is what the server reads at runtime — useful when you override',
  'a single value from a launcher or a container, not something you need to set by hand.',
  '',
  '## Settings',
  '',
];

for (const section of SECTIONS) {
  const settings = SETTINGS.filter(s => s.section === section.id);
  if (settings.length === 0) continue;
  lines.push(`### ${section.title}`, '', section.description, '');
  lines.push('| Key | Asked | Env var | Default | Description |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const setting of settings) {
    const choices = setting.choices?.length
      ? ' Values: ' + setting.choices.map(c => '`' + c.value + '` — ' + c.hint).join('; ') + '.'
      : '';
    lines.push(
      `| \`${setting.path}\` | ${TIER_LABEL[setting.tier]} | \`${setting.env}\` | ${formatDefault(setting)} | ` +
      `${escapeCell(setting.description + choices)} |`,
    );
  }
  lines.push('');
}

lines.push(
  '## File shapes',
  '',
  '`config/d365fo-mcp.json` — every key is optional; the wizard writes only what you answered:',
  '',
  '```json',
  buildExample('config'),
  '```',
  '',
  '`config/secrets.json` — git-ignored and written owner-only:',
  '',
  '```json',
  buildExample('secret'),
  '```',
  '',
);

writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outPath} (${SETTINGS.length} settings across ${SECTIONS.length} sections)`);
